### ISSUE TITLE
Character Names Messed Up

### ISSUE THREAD

**Issue by Nokocchii** [trainer17/Magical-Editor#1]
When changing main characters to both, when I play the game, the letters are messed up (the "c" become a cent icon), and the boy character's name is stuck as "Garret"

**Comment by trainer17** [comment]
Thanks for trying the editor out!

- I fixed the issue about the cent icon a few months ago, but never uploaded the updated version. I'm planning on a bigger update that includes a lot more features, and was waiting to finish it before updating this project. I realize now that I won't be able to work on it for still a few months, so I'll try to post the fix this weekend.

- The game does not store both the Male and Female character names in the .sav, so you can't choose both character's names. I will include this feature in the next update!

**Comment by Nokocchii** [comment]
Great, thank you! looking forward to it :)

Also, is there any way for the "default" name of the Male character to be switched to Galette, rather than Garret, in the cent icon update? Thanks!

**Comment by trainer17** [comment]
The name fix is done! Please let me know if you encounter any other issues.

I'll upload tomorrow a patch that let's you change the MC default name. It's not hard but you'll need to patch the game ROM for that. I'll let you know when it's up

**Comment by trainer17** [comment]
The name changer patcher is up! Please check the "Readme.txt" for instructions, or  let me know if you need help or something isn't working as expected

**Comment by Nokocchii** [comment]
Yay thank you so much!
